= Header Enricher Function

This module provides a header enricher function that can be reused and composed in other applications.

== Beans for injection

The `HeaderEnricherFunctionConfiguration` auto-configuration provides the following bean:

`headerEnricherFunction`

You can use `headerEnricherFunction` as a qualifier when injecting.

Once injected, you can use the `apply` method of the `Function` to invoke it and get the result.

== Configuration Options

For more information on the various options available, please see link:src/main/java/org/springframework/cloud/fn/header/enricher/HeaderEnricherFunctionProperties.java[HeaderEnricherFunctionProperties.java]

== Tests

See this link:src/test/java/org/springframework/cloud/fn/header/enricher/HeaderEnricherFunctionApplicationTests.java[test suite] for examples of how this function is used.

== Other usage

See this https://github.com/spring-cloud/stream-applications/blob/main/applications/processor/header-enricher-processor/README.adoc[README] where this function is used to create a Spring Cloud Stream application.