= Header Enricher Function

This module provides a header enricher function that can be reused and composed in other applications.

== Beans for injection

The `HeaderEnricherFunctionConfiguration` auto-configuration provides the following bean:

`headerFilterFunction`

You can use `headerFilterFunction` as a qualifier when injecting.

Once injected, you can use the `apply` method of the `Function` to invoke it and get the result.

== Configuration Options

For more information on the various options available, please see link:src/main/java/org/springframework/cloud/fn/header/filter/HeaderFilterFunctionProperties.java[HeaderFilterFunctionProperties.java]

== Tests

See this link:src/test/java/org/springframework/cloud/fn/header/filter/HeaderFilterFunctionApplicationTests.java[test suite] for examples of how this function is used.

== Other usage

See this link:../../../applications/processor/header-filter-processor/README.adoc[README] where this function is used to create a Spring Cloud Stream application.