= Filter Function

This module provides a filter function that can be reused and composed in other applications.

== Beans for injection

The `FilterFunctionConfiguration` auto-configuration provides following bean:

`filterFunction`

You can use `filterFunction` as a qualifier when injecting.

Once injected, you can use the `apply` method of the `Function` to invoke it and get the result.

== Configuration Options

All configuration properties are prefixed with `filter.function`.

For more information on the various options available, please see link:src/main/java/org/springframework/cloud/fn/filter/FilterFunctionProperties.java[FilterFunctionProperties.java]

== Examples

See this link:src/test/java/org/springframework/cloud/fn/filter/FilterFunctionApplicationTests.java[test suite] for examples of how this function is used.

== Other usage

See this https://github.com/spring-cloud/stream-applications/blob/main/applications/processor/filter-processor/README.adoc[README] where this function is used to create a Spring Cloud Stream application.