name: Pull Request Build

on:
  pull_request:
    branches:
      - main

jobs:
  build-pull-request:
    uses: spring-io/spring-github-workflows/.github/workflows/spring-gradle-pull-request-build.yml@v5
